services:
  - type: web
    name: pryMongoEsp32D
    runtime: python
    repo: https://github.com/Dani-RCD/pryMongoEsp32.git
    plan: free
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://dani:<db_password>@cluster0.kgcikfo.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
version: "1"
